version: "3.8"
services:
  mongo:
    container_name: gerenciadorleads-mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "${DB_LOCATION}:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
